# script to submit jobs to the grid for sn simulation

notify_user         = emanuele.villa@cern.ch
notification        = Always

JOBNAME             = sn-simulation
executable          = /afs/cern.ch/work/e/evilla/private/dune/dunesw/verbose-dev/run-sn-simulation.sh
# arguments           = 
output              = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).out
error               = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).err
log                 = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).log
request_cpus        = 1
# request_memory      = 2000

#requirements = (OpSysAndVer =?= "CentOS7")
MY.WantOS = "el7"
+JobFlavour         = "longlunch"


queue arguments from (
    # clean events first
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 2 -e jobCheck
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 400 -e 5
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 400 -e 6
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 400 -e 7
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 400 -e 8
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES -g -d -r -n 400 -e 5
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES -g -d -r -n 400 -e 6
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES -g -d -r -n 400 -e 7
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES -g -d -r -n 400 -e 8
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 10
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 11
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 12
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 13
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 14
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 15
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 16
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 17
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 18
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 19
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 10
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 11
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 12
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 13
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 14
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 15
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 16
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 17
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 18
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 19
)
