# script to submit jobs to the grid for sn simulation

notify_user         = emanuele.villa@cern.ch
notification        = Error

JOBNAME             = sn-standard-ES-with-bkg
executable          = /afs/cern.ch/work/e/evilla/private/dune/dunesw/verbose-dev/run-sn-simulation.sh
arguments           = -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 2 -f $(ProcId)
output              = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).out
error               = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).err
log                 = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).log
# request_cpus        = 1
# request_memory      = 2000

#requirements = (OpSysAndVer =?= "CentOS7")
MY.WantOS = "el7"
+JobFlavour         = "longlunch"
#+MaxRunTime        = 1800

queue 1

#queue arguments from (
#    -m prodmarley_nue_flat_clean_dune10kt_1x2x6_ES --custom-energy 2 5 -g -d -r -n 2 -f 2_to_5_MeV
#)
