# script to submit jobs to the grid for sn simulation

notify_user         = emanuele.villa@cern.ch
notification        = Always

JOBNAME             = sn-simulation
executable          = /afs/cern.ch/work/e/evilla/private/dune/dunesw/verbose-dev/run-sn-simulation.sh
arguments           = -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 1 -e testJob$(ClusterId)
output              = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).out
error               = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).err
log                 = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).log
request_cpus        = 1
# request_memory      = 2000

requirements = (OpSysAndVer =?= "CentOS7")
+JobFlavour         = "espresso"


queue
