# script to submit jobs to the grid for sn simulation

notify_user         = emanuele.villa@cern.ch
notification        = Error

JOBNAME             = sn-versor-direction-001-batch1star
executable          = /afs/cern.ch/work/e/evilla/private/dune/dunesw/verbose-dev/run-sn-simulation.sh
arguments           = -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 200 -f 1$(ProcId)
output              = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).out
error               = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).err
log                 = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).log
request_cpus        = 1
# request_memory      = 2000

requirements = (OpSysAndVer =?= "CentOS7")
#MY.WantOS = "el7"
+JobFlavour         = "longlunch"
#+MaxRunTime        = 1800

queue 100

