# script to submit jobs to the grid for sn simulation

notify_user         = emanuele.villa@cern.ch
notification        = Always

JOBNAME             = sn-versor-directions-failed
executable          = /afs/cern.ch/work/e/evilla/private/dune/dunesw/verbose-dev/run-sn-simulation.sh
# arguments           = 
output              = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).out
error               = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).err
log                 = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).log
request_cpus        = 1
# request_memory      = 2000

#requirements = (OpSysAndVer =?= "CentOS7")
MY.WantOS = "el7"
+JobFlavour         = "longlunch"


queue arguments from (
    # clean events, spectrum
    # direction 0 0 1
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction001 -g -d -r -n 500 -f 0
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction001 -g -d -r -n 500 -f 1
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction001 -g -d -r -n 500 -f 2
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction001 -g -d -r -n 500 -f 3
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction001 -g -d -r -n 500 -f 4
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction001 -g -d -r -n 500 -f 5
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction001 -g -d -r -n 500 -f 6
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction001 -g -d -r -n 500 -f 7
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction001 -g -d -r -n 500 -f 8
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction001 -g -d -r -n 500 -f 9
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 500 -f 0
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 500 -f 1
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 500 -f 2
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 500 -f 3
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 500 -f 4
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 500 -f 5
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 500 -f 6
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 500 -f 7
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 500 -f 8
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction001 -g -d -r -n 500 -f 9
    # direction 0 1 0
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction010 -g -d -r -n 500 -f 0
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction010 -g -d -r -n 500 -f 1
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction010 -g -d -r -n 500 -f 2
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction010 -g -d -r -n 500 -f 3
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction010 -g -d -r -n 500 -f 4
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction010 -g -d -r -n 500 -f 5
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction010 -g -d -r -n 500 -f 6
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction010 -g -d -r -n 500 -f 7
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction010 -g -d -r -n 500 -f 8
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction010 -g -d -r -n 500 -f 9
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction010 -g -d -r -n 500 -f 0
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction010 -g -d -r -n 500 -f 1
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction010 -g -d -r -n 500 -f 2
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction010 -g -d -r -n 500 -f 3
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction010 -g -d -r -n 500 -f 4
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction010 -g -d -r -n 500 -f 5
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction010 -g -d -r -n 500 -f 6
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction010 -g -d -r -n 500 -f 7
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction010 -g -d -r -n 500 -f 8
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction010 -g -d -r -n 500 -f 9
    # direction 1 0 0
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction100 -g -d -r -n 500 -f 0
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction100 -g -d -r -n 500 -f 1
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction100 -g -d -r -n 500 -f 2
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction100 -g -d -r -n 500 -f 3
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction100 -g -d -r -n 500 -f 4
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction100 -g -d -r -n 500 -f 5
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction100 -g -d -r -n 500 -f 6
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction100 -g -d -r -n 500 -f 7
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction100 -g -d -r -n 500 -f 8
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC_direction100 -g -d -r -n 500 -f 9
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction100 -g -d -r -n 500 -f 0
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction100 -g -d -r -n 500 -f 1
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction100 -g -d -r -n 500 -f 2
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction100 -g -d -r -n 500 -f 3
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction100 -g -d -r -n 500 -f 4
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction100 -g -d -r -n 500 -f 5
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction100 -g -d -r -n 500 -f 6
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction100 -g -d -r -n 500 -f 7
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction100 -g -d -r -n 500 -f 8
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES_direction100 -g -d -r -n 500 -f 9
)
