# script to submit jobs to the grid for sn simulation

notify_user         = emanuele.villa@cern.ch
notification        = Always

JOBNAME             = sn-simulation
executable          = run-sn-simulation.sh
# arguments           = 
output              = job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).out
error               = job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).err
log                 = job_output/job.$(JOBNAME).$(ClusterId).log
request_cpus        = 1
# request_memory      = 2000

requirements = (OpSysAndVer =?= "CentOS7")
+JobFlavour         = "microcentury"
# +MaxRunTime = 300 


queue arguments from (
    # clean events first
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 2 -e jobCheck
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 400 -e 0
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 400 -e 1
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 400 -e 2
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 400 -e 3
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 400 -e 4
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES -g -d -r -n 400 -e 0
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES -g -d -r -n 400 -e 1
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES -g -d -r -n 400 -e 2
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES -g -d -r -n 400 -e 3
    -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES -g -d -r -n 400 -e 4
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 0
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 1
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 2
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 3
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 4
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 5
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 6
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 7
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 8
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES -g -d -r -n 15 -e 9
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 0
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 1
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 2
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 3
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 4
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 5
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 6
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 7
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 8
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 15 -e 9
)
