    # script to submit jobs to the grid for sn simulation

    notify_user         = emanuele.villa@cern.ch
    notification        = Error

    JOBNAME             = sn-custom-energy-ranges-20_to_30-ES-clean
    executable          = /afs/cern.ch/work/e/evilla/private/dune/dunesw/verbose-dev/run-sn-simulation.sh
    arguments           = -m prodmarley_nue_flat_clean_dune10kt_1x2x6_ES --custom-energy 20 30 -g -d -r -n 50 -f 20-to-30-MeV_$(ProcId)
    output              = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).out
    error               = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).err
    log                 = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).log
    # request_cpus        = 1
    # request_memory      = 2000

    #requirements = (OpSysAndVer =?= "CentOS7")
    MY.WantOS = "el7"
    +JobFlavour         = "longlunch"
    #+MaxRunTime        = 1800

    queue 2    
