# script to submit jobs to the grid for sn simulation

notify_user         = emanuele.villa@cern.ch
notification        = Error

JOBNAME             = sn-standard-CC-with-bkg
executable          = /afs/cern.ch/work/e/evilla/private/dune/dunesw/verbose-dev/run-sn-simulation.sh
#arguments           = -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC_modifiedBkgRate -g -d -r -n 10 -f $(ProcId)
# line to run things that failed
arguments           = -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 10 -f 4
output              = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).out
error               = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).err
log                 = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).log
# request_cpus        = 1
# request_memory      = 2000

requirements = (OpSysAndVer =?= "CentOS7")
#MY.WantOS = "el7"
+JobFlavour         = "workday"
#+MaxRunTime        = 1800

queue 10
 
