# script to submit jobs to the grid for sn simulation

notify_user         = emanuele.villa@cern.ch
notification        = Error

JOBNAME             = sn-custom-direction-3D-pointing
executable          = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/scripts/run-sn-simulation.sh
arguments           = -m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES --custom-direction -g -d -r -n 350 -f 11$(ProcId)
output              = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).out
error               = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).err
log                 = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).log
request_cpus        = 1
# request_memory      = 2000

requirements = (OpSysAndVer =?= "CentOS7")
#MY.WantOS = "el7"
+JobFlavour         = "workday"
#+MaxRunTime        = 1800

queue 50


#queue arguments from (
    # custom directions, output will have _customDirection after the marley fcl name
    # for the ones run at 18:00 on Jan 16th, y = 0
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_CC -g -d -r -n 2 -f jobCheck
    #-m prodmarley_nue_spectrum_clean_dune10kt_1x2x6_ES -c -g -d -r -n 500 -f $(ProcId)
#)
