# script to submit jobs to the grid for sn simulation

notify_user         = emanuele.villa@cern.ch
notification        = Error

JOBNAME             = speed-test-CC-directions
executable          = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/run-sn-simulation.sh
#arguments           = -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_ES_modifiedBkgRate -g -d -r WFdump.fcl -n 10 -f $(ProcId)
# line to run things that failed
#arguments           = -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -g -d -r -n 10 -f 4
output              = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).out
error               = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).$(ProcId).err
log                 = /afs/cern.ch/work/e/evilla/private/dune/dunesw/dunesw-config/job_output/job.$(JOBNAME).$(ClusterId).log
# request_cpus        = 1
# request_memory      = 2000

requirements = (OpSysAndVer =?= "CentOS7")
#MY.WantOS = "el7"
+JobFlavour         = "workday"
#+MaxRunTime        = 1800

queue arguments from (
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 5 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 10 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 15 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 20 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 30 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 40 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 50 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 60 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 70 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 80 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 90 -f testSpeedCC
    -m prodmarley_nue_spectrum_radiological_decay0_dune10kt_refactored_1x2x6_CC -n 100 -f testSpeedCC
)
 
